_wandb:
    value:
        cli_version: 0.25.1
        e:
            otxqpyvzbvy6cpdetahvov5jhwwr5jw5:
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "502392610816"
                        used: "161637761024"
                email: ivancheremisin356@gmail.com
                executable: /home/askakolbaska/graph_LP/.venv/bin/python
                git:
                    commit: 7e1fe7d2b115a0670077e716ea12f7ec1d7f53f3
                    remote: git@github.com:askakolbaska1/graph_LP.git
                gpu: AMD Radeon RX 6800 XT
                gpu_amd:
                    - id: "0"
                      maxPower: "272.0"
                      model: "0x73bf"
                      performanceLevel: auto
                      series: AMD Radeon RX 6800 XT
                      sku: "001"
                      uniqueId: "0xaace5fff220e980b"
                      vbiosVersion: 113-001-X01
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                gpu_count: 1
                host: askakolbaska-desktop
                memory:
                    total: "33573789696"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: -m src.main
                python: CPython 3.12.3
                root: /home/askakolbaska/graph_LP
                startedAt: "2026-03-23T16:44:26.710223Z"
                writerId: otxqpyvzbvy6cpdetahvov5jhwwr5jw5
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 11
                - 49
                - 77
            "2":
                - 1
                - 11
                - 49
                - 77
            "3":
                - 2
                - 16
            "4": 3.12.3
            "5": 0.25.1
            "6": 5.1.0
            "12": 0.25.1
            "13": linux-x86_64
data_params:
    value:
        device: cuda
        heads_col: id_entity_1
        input_path: data/edges/clean_triples.csv
        predicates_col: predicate
        tails_col: id_entity_2
        test_and_val_size: 0.1
        train_size: 0.8
model_params:
    value:
        hidden_channels: 128
        margin: 1
model_type:
    value: distmult
random_seed:
    value: 42
test_params:
    value:
        "N": 3000
        batch_size: 8192
        k_list:
            - 1
            - 5
            - 10
            - 50
        log: true
        sampling: false
train_params:
    value:
        batch_size: 8192
        epochs: 5
        lr: 0.001
        sampler: sns
